### ISSUE TITLE
Makes ESC do nothing?

### ISSUE THREAD

**Issue by rsValliance** [rsfost/legacy-escape#1]
Hey, 

Just downloaded this plugin because i liked the sound of not accidentally closing "Click here to continue" and other similar chatbox prompts with ESC.

but it seems like it just.... outright removes ESC from functioning at all? I have the setting turned on to close interfaces in game settings (and tried with that turned off too).

I play in Modern Resizeable. I had an ESC F-Key keybind but tried with that unbound. I tried disabling any plugins i thought might interact weirdly with it (Global F-Keys, didn't change anything).

So is the purpose of this plugin to just outright disable the ESC keys functions? Which is just achievable with a Game setting?

Or is the main purpose of this plugin what I thought and the description says, where it makes it close interfaces but not chatbox interfaces?

it doesn't seem to work **at all** currently.

**RuneLite Version**: 1.10.37.1
**Oldschool revision**: Rev 225
**Launcher version**: 2.7.1
**OS**: Windows 10
**Other Details:** Modern resizable. Interface panels can't be closed with same F key. ESC bound to Prayer (but tested without). Tested with ESC closes interface game setting on and off.

**Comment by rsfost** [comment]
Your description of how the plugin is supposed to work is correct (should allow escape to close all interfaces except those appearing in the chatbox). I only tested the plugin on a Linux machine for some niche uses in barbarian assault, but I'll try your setup when I get a chance.

Are you able to close the bank interface and skill guide interfaces with the plugin enabled?

**Comment by rsValliance** [comment]
> Are you able to close the bank interface and skill guide interfaces with the plugin enabled?

I tried:

- Closing Bank interface
- Closing skill guides
- Closing settings menu

None of the above worked, with plugin off and standard game setting on it worked as expected.

**Comment by rsfost** [comment]
Thanks for reporting this. The fix is in the queue for the plugin hub.
